## Post settings ##
ShowShareButtons = false
ShowReadingTime = true
displayFullLangName = true
ShowPostNavLinks = true
ShowCodeCopyButtons = true
ShowToc = true
TocOpen = false

#### End of Landing Page Settings ####

## SEO Enhance ##
env = "production"

## Author ##
author = "AidenCLX"