# English Landing Page Settings
languageName = ":us: EN"
weight = 1
contentDir = "content/en"

## Taxonomies Settings for English Keywords
[taxonomies]
category = "categories"
tag = "tags"

[params.profileMode]
enabled = true
title = "Aiden at Poffy亭"
subtitle = "My corner for posting random stuff"
imageUrl = "profilePhoto.jpg"
imageWidth = "150"
imageHeight = "150"

[[params.profileMode.buttons]]
name = "Posts"
url = "posts"

[[params.profileMode.buttons]]
name = "About"
url = "about"

## Social Network Hyperlinks ##
[[params.socialIcons]]
name = "instagram"
url = "https://instagram.com/aidenclx"

[[params.socialIcons]]
name = "github"
url = "https://github.com/AidenKitamura"

[[params.socialIcons]]
name = "telegram"
url = "https://t.me/une_barque"

[[params.socialIcons]]
name = "email"
url = "mailto:kitamurainosuke@gmail.com"

[[params.socialIcons]]
name = "rss"
url = "localhost:1313/en/posts/index.xml"

# Menu Settings
[[menu.main]]
identifier = "Posts"
name = "Posts"
url = "posts"
weight = 10

[[menu.main]]
identifier = "Categories"
name = "Categories"
url = "categories"
weight = 20

#[[menu.main]]
#identifier = "Tags"
#name = "Tags"
#url = "tags"
#weight = 30

#[[menu.main]]
#identifier = "Archives"
#name = "Archives"
#url = "archives"
#weight = 40

[[menu.main]]
identifier = "Search"
name = "🔎︎"
url = "search"
weight = 50

[[menu.main]]
identifier = "About"
name = "About"
url = "about"
weight = 40

[[menu.main]]
identifier = "Links"
name = "Links"
url = "links"
weight = 40