## Social Network Hyperlinks ##
[[socialIcons]]
name = "instagram"
url = "https://instagram.com/aidenclx"

[[socialIcons]]
name = "github"
url = "https://github.com/AidenKitamura"

[[socialIcons]]
name = "telegram"
url = "https://t.me/une_barque"

[[socialIcons]]
name = "email"
url = "mailto:xu_aiden@outlook.com"

#### End of Landing Page Settings ####

## Post settings ##
showShareButtons = "true"
showReadingTime = "true"
showPostNavLinks = "true"
showCodeCopyButtons = "true"
showToc = "true"